### ISSUE TITLE
AWS::SSO::PermissionSet.InlinePolicy Accept Struct 

### ISSUE THREAD

**Issue by georgealton** [aws-cloudformation/aws-cloudformation-resource-providers-sso#6]
The data accepted by a [PermissionSet InlinePolicy requires a String](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sso-permissionset.html#cfn-sso-permissionset-inlinepolicy). 

Accepting a Structure here would make it easier to maintain and manage these Policies. 

PolicyDocuments in different IAM CloudFormation Resources accept structures

- [AWS::IAM::ManagedPolicy.PolicyDocument](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-managedpolicy.html#cfn-iam-managedpolicy-policydocument)
- [AWS::IAM::Policy.PolicyDocument](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-policy.html#cfn-iam-policy-policydocument)
- [AWS::IAM::Group.Policy.PolicyDocument](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iam-policy-2.html#cfn-iam-policies-policydocument)
- [AWS::S3::BucketPolicy.PolicyDocument](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-policy.html#aws-properties-s3-policy-policydocument)

It would then be possible to use [AWS::Include](
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/create-reusable-transform-function-snippets-and-add-to-your-template-with-aws-include-transform.html), externally defining the Policies from each PermissionSet. This provides a way of reusing Policies across PermissionsSets - which you may want to for Naming/RelayState Configuration.

DRYing up PolicyDocuments would reduce security issues from failing to apply the changes across mutliple resources. It would also allow those policies to be linted by tools like [Parliament](https://github.com/duo-labs/parliament)

Thanks!

**Comment by andriiglukhyi** [comment]
Hey George, thanks for pointing out.  We are working on the new release, which should change  policy type.

**Comment by georgealton** [comment]
Thanks! That's great to hear!

**Comment by andriiglukhyi** [comment]
Hey George, Inline policy can be represent as Struct.
Please let us know if you have any issue.
